services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-eng-assignment:latest
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host $${APP_HOST} --port $${APP_PORT}"

  db:
    image: postgres:16-alpine
    env_file:
      - .env

    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
